#ifndef PARAMS_H
#define PARAMS_H

#define LWR_N 256
//#define LWR_N 32
#define LWR_K 3
#define LWR_KS 4 /* used in sampler */
//#define LWR_Q 16384 //2^14
#define LWR_Q 8192 //2^13
//#define LWR_P 2048
#define LWR_P 1024
#define LWR_DELTA 3 /*Number of reconciliation bits */

#define LWR_SEEDBYTES       32
#define LWR_NOISESEEDBYTES  32
#define LWR_COINBYTES       32
#define LWR_KEYBYTES        32
#define LWR_MU 8
#define LWR_HASHBYTES       32

//#define LWR_POLYBYTES              448 //14*256/8 
#define LWR_POLYBYTES              416 //13*256/8 

#define LWR_POLYVECBYTES           (LWR_K * LWR_POLYBYTES)   

//#define LWR_POLYVECCOMPRESSEDBYTES (LWR_K * 352) //11*256/8
#define LWR_POLYVECCOMPRESSEDBYTES (LWR_K * 320) //10*256/8 NOTE : changed till here due to parameter adaptation

#define LWR_CIPHERTEXTBYTES (LWR_POLYVECCOMPRESSEDBYTES)

#define LWR_RECONBYTES (LWR_DELTA*LWR_N/8)

#define LWR_RECONBYTES_KEM ((LWR_DELTA+1)*LWR_N/8)

#define LWR_INDCPA_PUBLICKEYBYTES (LWR_POLYVECCOMPRESSEDBYTES + LWR_SEEDBYTES)
#define LWR_INDCPA_SECRETKEYBYTES (LWR_POLYVECBYTES)

#define LWR_PUBLICKEYBYTES (LWR_INDCPA_PUBLICKEYBYTES)

#define LWR_SECRETKEYBYTES (LWR_INDCPA_SECRETKEYBYTES +  LWR_INDCPA_PUBLICKEYBYTES + LWR_HASHBYTES + LWR_KEYBYTES)

#define LWR_BYTES_CCA_DEC   (LWR_POLYVECCOMPRESSEDBYTES + LWR_RECONBYTES_KEM) /* Second part is for Targhi-Unruh */



#define SABER_INDCPA_PUBLICKEYBYTES LWR_INDCPA_PUBLICKEYBYTES
#define SABER_INDCPA_SECRETKEYBYTES LWR_INDCPA_SECRETKEYBYTES
#define SABER_SECRETKEYBYTES LWR_SECRETKEYBYTES
#define SABER_KEYBYTES LWR_KEYBYTES
#define SABER_BYTES_CCA_DEC LWR_BYTES_CCA_DEC


#endif

